/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as NonAuthRoutesImport } from './routes/~_nonAuthRoutes'
import { Route as AuthRoutesImport } from './routes/~_authRoutes'
import { Route as NonAuthRoutesLoginImport } from './routes/~_nonAuthRoutes/~login'
import { Route as AuthRoutesIndexImport } from './routes/~_authRoutes/~index'
import { Route as AuthRoutesTransactionsIndexImport } from './routes/~_authRoutes/~transactions/~index'
import { Route as AuthRoutesSettingsIndexImport } from './routes/~_authRoutes/~settings/~index'
import { Route as AuthRoutesAnalyticsIndexImport } from './routes/~_authRoutes/~analytics/~index'
import { Route as AuthRoutesSettingsAccountsNewImport } from './routes/~_authRoutes/~settings/~accounts/~new'
import { Route as AuthRoutesSettingsCategoriesIndexImport } from './routes/~_authRoutes/~settings/~categories/~index'
import { Route as AuthRoutesSettingsAccountsIndexImport } from './routes/~_authRoutes/~settings/~accounts/~index'
import { Route as AuthRoutesSettingsAccountsRequisitionCallbackImport } from './routes/~_authRoutes/~settings/~accounts/~requisition/~callback'
import { Route as AuthRoutesSettingsAccountsAccountIdIndexImport } from './routes/~_authRoutes/~settings/~accounts/~$accountId/~index'

// Create/Update Routes

const NonAuthRoutesRoute = NonAuthRoutesImport.update({
  id: '/_nonAuthRoutes',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoutesRoute = AuthRoutesImport.update({
  id: '/_authRoutes',
  getParentRoute: () => rootRoute,
} as any)

const NonAuthRoutesLoginRoute = NonAuthRoutesLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NonAuthRoutesRoute,
} as any)

const AuthRoutesIndexRoute = AuthRoutesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoutesRoute,
} as any)

const AuthRoutesTransactionsIndexRoute =
  AuthRoutesTransactionsIndexImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthRoutesRoute,
  } as any)

const AuthRoutesSettingsIndexRoute = AuthRoutesSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoutesRoute,
} as any)

const AuthRoutesAnalyticsIndexRoute = AuthRoutesAnalyticsIndexImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AuthRoutesRoute,
} as any)

const AuthRoutesSettingsAccountsNewRoute =
  AuthRoutesSettingsAccountsNewImport.update({
    id: '/settings/accounts/new',
    path: '/settings/accounts/new',
    getParentRoute: () => AuthRoutesRoute,
  } as any)

const AuthRoutesSettingsCategoriesIndexRoute =
  AuthRoutesSettingsCategoriesIndexImport.update({
    id: '/settings/categories/',
    path: '/settings/categories/',
    getParentRoute: () => AuthRoutesRoute,
  } as any)

const AuthRoutesSettingsAccountsIndexRoute =
  AuthRoutesSettingsAccountsIndexImport.update({
    id: '/settings/accounts/',
    path: '/settings/accounts/',
    getParentRoute: () => AuthRoutesRoute,
  } as any)

const AuthRoutesSettingsAccountsRequisitionCallbackRoute =
  AuthRoutesSettingsAccountsRequisitionCallbackImport.update({
    id: '/settings/accounts/requisition/callback',
    path: '/settings/accounts/requisition/callback',
    getParentRoute: () => AuthRoutesRoute,
  } as any)

const AuthRoutesSettingsAccountsAccountIdIndexRoute =
  AuthRoutesSettingsAccountsAccountIdIndexImport.update({
    id: '/settings/accounts/$accountId/',
    path: '/settings/accounts/$accountId/',
    getParentRoute: () => AuthRoutesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authRoutes': {
      id: '/_authRoutes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRoutesImport
      parentRoute: typeof rootRoute
    }
    '/_nonAuthRoutes': {
      id: '/_nonAuthRoutes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NonAuthRoutesImport
      parentRoute: typeof rootRoute
    }
    '/_authRoutes/': {
      id: '/_authRoutes/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthRoutesIndexImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_nonAuthRoutes/login': {
      id: '/_nonAuthRoutes/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NonAuthRoutesLoginImport
      parentRoute: typeof NonAuthRoutesImport
    }
    '/_authRoutes/analytics/': {
      id: '/_authRoutes/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthRoutesAnalyticsIndexImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_authRoutes/settings/': {
      id: '/_authRoutes/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthRoutesSettingsIndexImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_authRoutes/transactions/': {
      id: '/_authRoutes/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthRoutesTransactionsIndexImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_authRoutes/settings/accounts/': {
      id: '/_authRoutes/settings/accounts/'
      path: '/settings/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof AuthRoutesSettingsAccountsIndexImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_authRoutes/settings/categories/': {
      id: '/_authRoutes/settings/categories/'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthRoutesSettingsCategoriesIndexImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_authRoutes/settings/accounts/new': {
      id: '/_authRoutes/settings/accounts/new'
      path: '/settings/accounts/new'
      fullPath: '/settings/accounts/new'
      preLoaderRoute: typeof AuthRoutesSettingsAccountsNewImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_authRoutes/settings/accounts/$accountId/': {
      id: '/_authRoutes/settings/accounts/$accountId/'
      path: '/settings/accounts/$accountId'
      fullPath: '/settings/accounts/$accountId'
      preLoaderRoute: typeof AuthRoutesSettingsAccountsAccountIdIndexImport
      parentRoute: typeof AuthRoutesImport
    }
    '/_authRoutes/settings/accounts/requisition/callback': {
      id: '/_authRoutes/settings/accounts/requisition/callback'
      path: '/settings/accounts/requisition/callback'
      fullPath: '/settings/accounts/requisition/callback'
      preLoaderRoute: typeof AuthRoutesSettingsAccountsRequisitionCallbackImport
      parentRoute: typeof AuthRoutesImport
    }
  }
}

// Create and export the route tree

interface AuthRoutesRouteChildren {
  AuthRoutesIndexRoute: typeof AuthRoutesIndexRoute
  AuthRoutesAnalyticsIndexRoute: typeof AuthRoutesAnalyticsIndexRoute
  AuthRoutesSettingsIndexRoute: typeof AuthRoutesSettingsIndexRoute
  AuthRoutesTransactionsIndexRoute: typeof AuthRoutesTransactionsIndexRoute
  AuthRoutesSettingsAccountsIndexRoute: typeof AuthRoutesSettingsAccountsIndexRoute
  AuthRoutesSettingsCategoriesIndexRoute: typeof AuthRoutesSettingsCategoriesIndexRoute
  AuthRoutesSettingsAccountsNewRoute: typeof AuthRoutesSettingsAccountsNewRoute
  AuthRoutesSettingsAccountsAccountIdIndexRoute: typeof AuthRoutesSettingsAccountsAccountIdIndexRoute
  AuthRoutesSettingsAccountsRequisitionCallbackRoute: typeof AuthRoutesSettingsAccountsRequisitionCallbackRoute
}

const AuthRoutesRouteChildren: AuthRoutesRouteChildren = {
  AuthRoutesIndexRoute: AuthRoutesIndexRoute,
  AuthRoutesAnalyticsIndexRoute: AuthRoutesAnalyticsIndexRoute,
  AuthRoutesSettingsIndexRoute: AuthRoutesSettingsIndexRoute,
  AuthRoutesTransactionsIndexRoute: AuthRoutesTransactionsIndexRoute,
  AuthRoutesSettingsAccountsIndexRoute: AuthRoutesSettingsAccountsIndexRoute,
  AuthRoutesSettingsCategoriesIndexRoute:
    AuthRoutesSettingsCategoriesIndexRoute,
  AuthRoutesSettingsAccountsNewRoute: AuthRoutesSettingsAccountsNewRoute,
  AuthRoutesSettingsAccountsAccountIdIndexRoute:
    AuthRoutesSettingsAccountsAccountIdIndexRoute,
  AuthRoutesSettingsAccountsRequisitionCallbackRoute:
    AuthRoutesSettingsAccountsRequisitionCallbackRoute,
}

const AuthRoutesRouteWithChildren = AuthRoutesRoute._addFileChildren(
  AuthRoutesRouteChildren,
)

interface NonAuthRoutesRouteChildren {
  NonAuthRoutesLoginRoute: typeof NonAuthRoutesLoginRoute
}

const NonAuthRoutesRouteChildren: NonAuthRoutesRouteChildren = {
  NonAuthRoutesLoginRoute: NonAuthRoutesLoginRoute,
}

const NonAuthRoutesRouteWithChildren = NonAuthRoutesRoute._addFileChildren(
  NonAuthRoutesRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof NonAuthRoutesRouteWithChildren
  '/': typeof AuthRoutesIndexRoute
  '/login': typeof NonAuthRoutesLoginRoute
  '/analytics': typeof AuthRoutesAnalyticsIndexRoute
  '/settings': typeof AuthRoutesSettingsIndexRoute
  '/transactions': typeof AuthRoutesTransactionsIndexRoute
  '/settings/accounts': typeof AuthRoutesSettingsAccountsIndexRoute
  '/settings/categories': typeof AuthRoutesSettingsCategoriesIndexRoute
  '/settings/accounts/new': typeof AuthRoutesSettingsAccountsNewRoute
  '/settings/accounts/$accountId': typeof AuthRoutesSettingsAccountsAccountIdIndexRoute
  '/settings/accounts/requisition/callback': typeof AuthRoutesSettingsAccountsRequisitionCallbackRoute
}

export interface FileRoutesByTo {
  '': typeof NonAuthRoutesRouteWithChildren
  '/': typeof AuthRoutesIndexRoute
  '/login': typeof NonAuthRoutesLoginRoute
  '/analytics': typeof AuthRoutesAnalyticsIndexRoute
  '/settings': typeof AuthRoutesSettingsIndexRoute
  '/transactions': typeof AuthRoutesTransactionsIndexRoute
  '/settings/accounts': typeof AuthRoutesSettingsAccountsIndexRoute
  '/settings/categories': typeof AuthRoutesSettingsCategoriesIndexRoute
  '/settings/accounts/new': typeof AuthRoutesSettingsAccountsNewRoute
  '/settings/accounts/$accountId': typeof AuthRoutesSettingsAccountsAccountIdIndexRoute
  '/settings/accounts/requisition/callback': typeof AuthRoutesSettingsAccountsRequisitionCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authRoutes': typeof AuthRoutesRouteWithChildren
  '/_nonAuthRoutes': typeof NonAuthRoutesRouteWithChildren
  '/_authRoutes/': typeof AuthRoutesIndexRoute
  '/_nonAuthRoutes/login': typeof NonAuthRoutesLoginRoute
  '/_authRoutes/analytics/': typeof AuthRoutesAnalyticsIndexRoute
  '/_authRoutes/settings/': typeof AuthRoutesSettingsIndexRoute
  '/_authRoutes/transactions/': typeof AuthRoutesTransactionsIndexRoute
  '/_authRoutes/settings/accounts/': typeof AuthRoutesSettingsAccountsIndexRoute
  '/_authRoutes/settings/categories/': typeof AuthRoutesSettingsCategoriesIndexRoute
  '/_authRoutes/settings/accounts/new': typeof AuthRoutesSettingsAccountsNewRoute
  '/_authRoutes/settings/accounts/$accountId/': typeof AuthRoutesSettingsAccountsAccountIdIndexRoute
  '/_authRoutes/settings/accounts/requisition/callback': typeof AuthRoutesSettingsAccountsRequisitionCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/login'
    | '/analytics'
    | '/settings'
    | '/transactions'
    | '/settings/accounts'
    | '/settings/categories'
    | '/settings/accounts/new'
    | '/settings/accounts/$accountId'
    | '/settings/accounts/requisition/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/login'
    | '/analytics'
    | '/settings'
    | '/transactions'
    | '/settings/accounts'
    | '/settings/categories'
    | '/settings/accounts/new'
    | '/settings/accounts/$accountId'
    | '/settings/accounts/requisition/callback'
  id:
    | '__root__'
    | '/_authRoutes'
    | '/_nonAuthRoutes'
    | '/_authRoutes/'
    | '/_nonAuthRoutes/login'
    | '/_authRoutes/analytics/'
    | '/_authRoutes/settings/'
    | '/_authRoutes/transactions/'
    | '/_authRoutes/settings/accounts/'
    | '/_authRoutes/settings/categories/'
    | '/_authRoutes/settings/accounts/new'
    | '/_authRoutes/settings/accounts/$accountId/'
    | '/_authRoutes/settings/accounts/requisition/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoutesRoute: typeof AuthRoutesRouteWithChildren
  NonAuthRoutesRoute: typeof NonAuthRoutesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoutesRoute: AuthRoutesRouteWithChildren,
  NonAuthRoutesRoute: NonAuthRoutesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/_authRoutes",
        "/_nonAuthRoutes"
      ]
    },
    "/_authRoutes": {
      "filePath": "~_authRoutes.tsx",
      "children": [
        "/_authRoutes/",
        "/_authRoutes/analytics/",
        "/_authRoutes/settings/",
        "/_authRoutes/transactions/",
        "/_authRoutes/settings/accounts/",
        "/_authRoutes/settings/categories/",
        "/_authRoutes/settings/accounts/new",
        "/_authRoutes/settings/accounts/$accountId/",
        "/_authRoutes/settings/accounts/requisition/callback"
      ]
    },
    "/_nonAuthRoutes": {
      "filePath": "~_nonAuthRoutes.tsx",
      "children": [
        "/_nonAuthRoutes/login"
      ]
    },
    "/_authRoutes/": {
      "filePath": "~_authRoutes/~index.tsx",
      "parent": "/_authRoutes"
    },
    "/_nonAuthRoutes/login": {
      "filePath": "~_nonAuthRoutes/~login.tsx",
      "parent": "/_nonAuthRoutes"
    },
    "/_authRoutes/analytics/": {
      "filePath": "~_authRoutes/~analytics/~index.tsx",
      "parent": "/_authRoutes"
    },
    "/_authRoutes/settings/": {
      "filePath": "~_authRoutes/~settings/~index.tsx",
      "parent": "/_authRoutes"
    },
    "/_authRoutes/transactions/": {
      "filePath": "~_authRoutes/~transactions/~index.tsx",
      "parent": "/_authRoutes"
    },
    "/_authRoutes/settings/accounts/": {
      "filePath": "~_authRoutes/~settings/~accounts/~index.tsx",
      "parent": "/_authRoutes"
    },
    "/_authRoutes/settings/categories/": {
      "filePath": "~_authRoutes/~settings/~categories/~index.tsx",
      "parent": "/_authRoutes"
    },
    "/_authRoutes/settings/accounts/new": {
      "filePath": "~_authRoutes/~settings/~accounts/~new.tsx",
      "parent": "/_authRoutes"
    },
    "/_authRoutes/settings/accounts/$accountId/": {
      "filePath": "~_authRoutes/~settings/~accounts/~$accountId/~index.tsx",
      "parent": "/_authRoutes"
    },
    "/_authRoutes/settings/accounts/requisition/callback": {
      "filePath": "~_authRoutes/~settings/~accounts/~requisition/~callback.tsx",
      "parent": "/_authRoutes"
    }
  }
}
ROUTE_MANIFEST_END */
